title: Meu Projeto

description: Documentação do meu projeto

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

nav:

  - Home: README.md

  - Data:

      - Introdução: Data/README.md

      - Input: Data/input/

      - Simulação: Data/simulação/

  - Plots: Plots/README.md

  - Scripts:

      - Introdução: Scripts/README.md

      - Análises: Scripts/análises/

      - Visualização: Scripts/visualização/
