title: Meu Projeto

description: Documentação do meu projeto

remote_theme: just-the-docs/just-the-docs

nav:

  - Home: README.md

  - Data:

      - Introdução: Data/README.md

      - Input: Data/input/

      - Simulação: Data/simulação/

  - Plots: Plots/README.md

  - Scripts:

      - Introdução: Scripts/README.md

      - Análises: Scripts/análises/

      - Visualização: Scripts/visualização/
